### PR TITLE
prevent automatic update of private_content_version

### PR DESCRIPTION
**Pull request by mvenghaus**

### CODE REVIEW

**Review by wpoortman — COMMENTED** [review]
Question: would this feature require something like protected $updatePrivateContent = false as default which could be changed into something like an array with the methods who require an update or if true, the private content will be updaten on each subsequent request no matter which method is being called?

Just brainfarting here. On my phone doing some MR reviewing. Will have a closer look as soon as get behind my macbook

**Comment by mvenghaus** [comment]
actually it has to be disabled by default .. because this makes so many unnecessary requests. but i think a lot of magewire integrations depending on this .. like hyva checkout :) if it's disabled the header mini cart is not updated on success page.

so i think the best solution would be to hava a variable like you mentioned.

**Comment by wpoortman** [comment]
The weird thing is though, I never seen this issue before. It there a specific way I can reproduce this, because e.g. in the checkout all components are just making one single XHR request, no additional private content requests are made. I just need a practical example on who to test this in order to merge it 😸

**Comment by mvenghaus** [comment]
it's not a problem of your checkout or any other integration.. it's a magento/hyva thing. after every post request the customer section load is triggered.

steps to reproduce:
- make post request
- refresh site
-> /customer/section/load/?sections= is loaded every time

**Comment by mvenghaus** [comment]
last PR open .. after all i think disabling private content version is not the solution .. too many problems.

my approach is to make to blak/whitelist ...

https://github.com/mvenghaus/magewire-plugin-private-content-version

this in good would be nice ;)

**Pull request closed without merging**
