### PR TITLE
added the ability to use magewire in dynamic created blocks or widgets

### PR DESCRIPTION
**Pull request by mvenghaus**

### CODE REVIEW

**Review by wpoortman — CHANGES_REQUESTED** [review]
@mvenghaus, great addition and really appreciate the work you've done!

I'm missing some documentation. Not only for others, but also for myself to fully understand how it should work and what we optionally could add in the future.

Could you also create a section for that within the docs Features & Examples markdown?

Thanks!

**Comment by mvenghaus** [comment]
@wpoortman added some documentation

**Comment by adamzero1** [comment]
It think this would be really useful, just hit this exact issue!

**Comment by adamzero1** [comment]
@mvenghaus / @wpoortman if there is anything I can do here to help things along, please let me know.
I'm trying to get this working with minicart buttons for applepay, but because the block has to be created dynamically it doesn't hook up correctly.

**Comment by wpoortman** [comment]
> @mvenghaus / @wpoortman if there is anything I can do here to help things along, please let me know. I'm trying to get this working with minicart buttons for applepay, but because the block has to be created dynamically it doesn't hook up correctly.

Thanks @adamzero1, really appreciate that. I'm currently working on a Magewire video course, which I hopefully finish tomorrow morning. I will swap my focus to these Pull Requests right away after that!

Maybe you could already test this PR in your instance to check if you spot any problems and if it solves your issue?

**Comment by adamzero1** [comment]
I had to change the following, as php 7.4 doesn't support spreading arrays with string keys
`vendor/magewirephp/magewire/src/Model/ComponentManager.php`
```
    return $this->httpFactory->createRequest([
            'fingerprint' => array_merge([
                'id' => $component->id,
                'name' => $component->name,
                'locale' => $locale,
                'path' => '/',
                'method' => 'GET',

                // Custom relative to Livewire's core.
                'handle' => $handle,
                'type' => $component::COMPONENT_TYPE,
            ], $this->getDynamicLayout($block, $component)),
            'serverMemo' => [
                'data' => $data
            ]
        ]);
```
Other then that appeared to work fine.
My component still isn't being registered though, so maybe this wasn't the issue or there is something else stopping it from working.

**Comment by adamzero1** [comment]
Just as a bit of an update I got around the other issue I was having, which allowed me to test this PR.
- without the PR, calling any action e.g `Magewire.find('foo.bar').call('test')` results in an error being returned, that a block with name x/y/z not found
- with the PR this appears to work as expected, I can call method on my Magewire component.

Only outstand question I have is around giving the component a nicer ID as the default one is pretty unweildy. I'm currently doing:
```php
$block= $shortcutButtons->getLayout()->createBlock(MyBlock::class);
$component = $this->objectManager->create(MagewireComponent::class);
$component->id = 'foo.bar';
$block->setData('magewire', $component);
```
Not sure if the is a better way?

**Comment by wpoortman** [comment]
> Just as a bit of an update I got around the other issue I was having, which allowed me to test this PR.
> 
> * without the PR, calling any action e.g `Magewire.find('foo.bar').call('test')` results in an error being returned, that a block with name x/y/z not found
> * with the PR this appears to work as expected, I can call method on my Magewire component.
> 
> Only outstand question I have is around giving the component a nicer ID as the default one is pretty unweildy. I'm currently doing:
> 
> ```
> $block= $shortcutButtons->getLayout()->createBlock(MyBlock::class);
> $component = $this->objectManager->create(MagewireComponent::class);
> $component->id = 'foo.bar';
> $block->setData('magewire', $component);
> ```
> 
> Not sure if the is a better way?

First of all, are you aware of the fact that you can just use test() instead of call('test')?

Thinking about a better way, I think we should create a factory class for it to avoid a lot of overhead and better maintainability for the future. It would give a lot of benefits. I'm gonna do some experimenting this afternoon, hope to get a good result soon.

**Comment by adamzero1** [comment]
> Are you aware of the fact that you can just use test() instead of call('test')?
I was not! Nice one!

> I think we should create a factory class for it
Yeah I think that would be a good solution. 
```php
$factory->create('foo.bar', Block::class, MagewireComponent::class);
```
Would certainly streamline, and would give flexibility/upgradability in the future if other setup bits were required.

**Comment by wpoortman** [comment]
@mvenghaus,

image

This is something I'm not to sure about. I really don't like full object paths being visible since in many cases you get situations where the agency building something, doesn't want their name in there or the customer doesn't want anyone to know who build it or how classes are named in general.

Also I think storing this in the `fingerprint` is not the right location. I think it should belong to the `serverMemo` with e.g. a key which is called `dynamic` (not sure about the name still haha).

**Suggestion / brainfart:**
What if you hash those object classes with the crypt key (or something else unique). That way we can decrypt it as soon as it comes back in the controller? You think that would work?

Also, I think we should re-use `\Model\ComponentFactory` with an additional function something like, `createBlock` or `createDynamicBlock` (still not sure). This method will accept a layout object, component class string, additional data array. Maybe it also requires a name, but that not important for now since if you ask me, I would also like a unique name. This factory creates the Block which is just inherited from `\Magento\Framework\View\Element\Template`. This can't be changed, since using custom blocks is not something anyone want. So we give the developer no choice if you get what I mean.

Running out of time for today, will continue tomorrow (evening).

**Comment by mvenghaus** [comment]
@wpoortman at first i stored the information in the layout cache .. but too many shop owners clear the cache in production (very often) and that would affect the users who have been already loaded a site. i've decided to put the information in the fingerprint because these information are needed to identify the request as unique.

i also thought about encryption. that should be no problem .. only for readability. so in dev mode it should be not encrypted and in production i think everything could be encrypted.

the creation of a block should be using a factory. i don't like the way i built it, but doesn't find another way without making much more changes. i thought you are more into it and find the perfect solution ;)

**Comment by wpoortman** [comment]
> the creation of a block should be using a factory. i don't like the way i built it, but doesn't find another way without making much more changes. i thought you are more into it and find the perfect solution ;)

Working on something cool, hopefully this is going the right way 😄

**Comment by wpoortman** [comment]
@mvenghaus,

I think we can close this MR since we now have the Component Resolver architecture in place. How do you think about that?

**Pull request closed without merging**
